### PR TITLE
Fixed ItemFrameDropItemPacket

### LINKED ISSUE #599: ItemFrame cannot be broken/items cannot be taken out
My English is very poor.. (Korean..)
I can't use ItemFrame But.. Genisys can use ItemFrame.  Help me!

----

Does not drop its item, its removed client side but not server side. after relog item back in item frame.

### PR DESCRIPTION
**Pull request by beito123**
Fixed the bug of ItemFrame does not drop the item.

Fixed #599

### CODE REVIEW

**Comment by inxomnyaa** [comment]
Cool stuff! Still, thanks that we can use your code.

File: src/pocketmine/network/Network.php [hunk 1]
```diff
@@ -330,6 +331,6 @@ private function registerPackets(){
 		// $this->registerPacket(ProtocolInfo::MAP_INFO_REQUEST_PACKET, MapInfoRequestPacket::class);
 		$this->registerPacket(ProtocolInfo::REQUEST_CHUNK_RADIUS_PACKET, RequestChunkRadiusPacket::class);
 		$this->registerPacket(ProtocolInfo::CHUNK_RADIUS_UPDATED_PACKET, ChunkRadiusUpdatedPacket::class);
-		// $this->registerPacket(ProtocolInfo::ITEM_FRAME_DROP_ITEM_PACKET, ItemFrameDropItemPacket::class);
```
Comment (inxomnyaa) [inline src/pocketmine/network/Network.php:333]: lol didnt saw this
